# Generated by Django 3.2 on 2021-04-28 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_questions_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='category',
            field=models.ForeignKey(default='JSS', on_delete=django.db.models.deletion.DO_NOTHING, to='quizapp.category'),
        ),
    ]
